### ISSUE TITLE
データセットの作り直し

### ISSUE THREAD

**Issue by Gitefu** [koji0919/C100#26]
# 目的
- ストーリーに合わせる

# 完成物の条件
- [ ] y軸となる「食べる量」
- [ ] 変数5つ
   - [ ] 3つのp値が0.05以下
   - [ ] 2つのp値が0.05以上

**Comment by koji0919** [comment]
説明変数の値の範囲どうしよ、標準化するから負の値があるのはいいとして、その値の大きさはいじる必要あるっけ?
