### ISSUE TITLE
顔の枠をkeynoteで作る

### ISSUE THREAD

**Issue by Gitefu** [koji0919/C100#40]
- [x] 表情描いたらテンプレにぶち込む
- [x] 天命を待つ
- [x] まゆすき
- [x] Keynote→PNGにする
  - `book/images/`に直接upする
- [x] ファイル名を揃える
  - ファイル名は`book/config-starter.yml`の下の方を見て参考にする．
  - 必要なら，本文(`book/contents/＊＊.re`)を書き換えて良い
- [x] PNGを本に反映する
  - やり方はbook/README.md見てね

**Comment by Salmonpan** [comment]
馴染むぞぉ

**Comment by Salmonpan** [comment]
このissueは乗っ取った！ジョースター！！！！
